<?php

namespace Main\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectRepository extends EntityRepository
{
}
