<?php

namespace Main\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectRepository extends EntityRepository
{
    public function findConnect($userId,$connectUserId){
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM MainApiBundle:Connect c JOIN c.userConnect e WHERE c.user = :connectUserId AND e.user = :userId')
            ->setParameter('userId', $userId)
            ->setParameter('connectUserId', $connectUserId)
            ->getOneOrNullResult();
    }
}
