<?php

namespace Main\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends EntityRepository
{
}
