security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    foo: { password: test }
        user_db:
            entity: { class: Main\ApiBundle\Entity\User, property: username }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        default:
#            anonymous: ~

        admin_area:
            pattern:    ^/admin
            http_basic: ~

        secured_area:
            pattern:    ^/
            provider: user_db
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: main_api_dashboard
            logout:
                path:   /logout
                target: /
    access_control:

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/dashboard$, role: ROLE_USER }
        - { path: ^/create-event$, role: ROLE_USER }
        - { path: ^/event/, role: ROLE_USER }
    encoders:
        "Main\ApiBundle\Entity\User": sha1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]