main_api_homepage:
    path:     /
    defaults: { _controller: MainApiBundle:Main:index }

main_api_dashboard:
    path:     /dashboard
    defaults: { _controller: MainApiBundle:Main:dashboard }

main_api_registration:
    path:     /registration
    defaults: { _controller: MainApiBundle:Registration:registration }

main_api_create_event:
    path:     /create-event
    defaults: { _controller: MainApiBundle:Event:createEvent }

main_api_add_participant:
    path:     /add-participant
    defaults: { _controller: MainApiBundle:Participant:addParticipant }

main_api_create_task:
    path:     /create-task
    defaults: { _controller: MainApiBundle:Task:createTask }

main_api_task_manager:
    path:     /task-manager
    defaults: { _controller: MainApiBundle:Task:taskManager }

main_api_event:
    path:     /event/{eventName}
    defaults: { _controller: MainApiBundle:Event:getEvent }

main_api_confirm_participant_notification:
    path:     /confirm-participant-notification
    defaults: { _controller: MainApiBundle:Notification:confirmParticipantNotification }

main_api_confirm_connect_notification:
    path:     /confirm-connect-notification
    defaults: { _controller: MainApiBundle:Notification:confirmConnectNotification }
main_api_notifications:
    path:     /notifications
    defaults: { _controller: MainApiBundle:Notification:viewNotifications }

main_api_connect_ajaxCall:
    path:     /connect
    defaults: { _controller: MainApiBundle:Connect:connect }

main_api_user:
    path:     /user/{userId}
    defaults: { _controller: MainApiBundle:User:view }

get_available_user:
    path:     /get-available-user
    defaults: { _controller: MainApiBundle:Participant:getAvailableUser }

get_available_participant:
    path:     /get-available-participant
    defaults: { _controller: MainApiBundle:Participant:getAvailableParticipant }
