Main\ApiBundle\Entity\Participant:
    type: entity
    repositoryClass: Main\ApiBundle\Repository\ParticipantRepository
    table: participant
    id:
        event:
          associationKey: true
        user:
          associationKey: true
        userUnder:
          associationKey: true
    fields:
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: participans
        user:
            targetEntity: User
            inversedBy: participans
        userUnder:
            targetEntity: User
            inversedBy: participans


    lifecycleCallbacks: {  }
