Main\ApiBundle\Entity\Participant:
    type: entity
    repositoryClass: Main\ApiBundle\Repository\ParticipantRepository
    table: participant
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
    manyToOne:
        user:
            targetEntity: User
            cascade: [persist]
            inversedBy: participans
            joinColumn:
                name: user_id
                referencedColumnName: id
            orphanRemoval: true
    oneToOne:
        eventUserParticipant:
            targetEntity: EventUserParticipant
            mappedBy: participant


    lifecycleCallbacks: {  }
