Main\ApiBundle\Entity\User:
    type: entity
    repositoryClass: Main\ApiBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            default: ''
        lastName:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            default: ''
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            default: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
            default: ''
        date:
            type: datetime
            nullable: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
    oneToMany:
        events:
            targetEntity: Event
            mappedBy: user
            cascade: [persist]
            orphanRemoval: true
        participans:
            targetEntity: Participant
            mappedBy: user
            cascade: [persist]
            orphanRemoval: true
        participans:
            targetEntity: Participant
            mappedBy: userUnder
            cascade: [persist]
            orphanRemoval: true
        works:
            targetEntity: Work
            mappedBy: user
            cascade: [persist]
            orphanRemoval: true
        works:
            targetEntity: Work
            mappedBy: userTo
            cascade: [persist]
            orphanRemoval: true
    lifecycleCallbacks: {  }
